package com.mvp.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mvp.db.greendao.ProductMess;
import com.mvp.db.greendao.SystemValues;

import com.mvp.db.greendao.ProductMessDao;
import com.mvp.db.greendao.SystemValuesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productMessDaoConfig;
    private final DaoConfig systemValuesDaoConfig;

    private final ProductMessDao productMessDao;
    private final SystemValuesDao systemValuesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productMessDaoConfig = daoConfigMap.get(ProductMessDao.class).clone();
        productMessDaoConfig.initIdentityScope(type);

        systemValuesDaoConfig = daoConfigMap.get(SystemValuesDao.class).clone();
        systemValuesDaoConfig.initIdentityScope(type);

        productMessDao = new ProductMessDao(productMessDaoConfig, this);
        systemValuesDao = new SystemValuesDao(systemValuesDaoConfig, this);

        registerDao(ProductMess.class, productMessDao);
        registerDao(SystemValues.class, systemValuesDao);
    }
    
    public void clear() {
        productMessDaoConfig.clearIdentityScope();
        systemValuesDaoConfig.clearIdentityScope();
    }

    public ProductMessDao getProductMessDao() {
        return productMessDao;
    }

    public SystemValuesDao getSystemValuesDao() {
        return systemValuesDao;
    }

}
